driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 512

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-10.04
    run_list:
    - recipe[apt::default]
  - name: centos-6.4
  - name: centos-5.9

suites:
- name: default
  run_list:
  - recipe[nagios::client]
