name             'nagios'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Provides resources to install and configure Nagios server'
version          '13.0.0'
issues_url       'https://github.com/sous-chefs/nagios/issues'
source_url       'https://github.com/sous-chefs/nagios'
chef_version     '>= 15.3'

depends 'apache2', '>= 9.0'
depends 'nginx', '>= 11.2'
depends 'php', '>= 10.0'
depends 'yum-epel'
depends 'zap', '>= 0.6.0'

supports 'almalinux', '>= 8.0'
supports 'centos_stream', '>= 9.0'
supports 'redhat', '>= 8.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'oracle', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'
